name: Build Binaries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: sudo apt install libarchive-tools rpm wine wine-mono
      - run: yarn
      - run: yarn dist
      - name: Archive Binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.deb
            dist/*.snap
            dist/*.pacman
            dist/*.tar.gz
            dist/*.rpm
            dist/*.AppImage
          retention-days: 5
