name: Build Binaries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: sudo apt install libarchive-tools wine
      - run: yarn
      - run: yarn dist-win
      - name: Archive Binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.msi
          retention-days: 5
