name: Build Binaries

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Prepare OS
        run: sudo apt install libarchive-tools rpm
      - name: Prepare Yarn
        run: yarn
      - name: Package for Linux
        run: yarn dist-linux
      - name: Archive Binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.deb
            dist/*.snap
            dist/*.pacman
            dist/*.tar.gz
            dist/*.rpm
            dist/*.AppImage
          retention-days: 5
  build-mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Prepare Yarn
        run: yarn
      - name: Package for Mac
        run: yarn dist-mac
      - name: Archive Binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.dmg
          retention-days: 5
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn
      - run: yarn dist-win
      - name: Archive Binaries
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/*.msi
          retention-days: 5
